# Tests, builds, and deploys a WordPress site to Runcloud.
# See https://git.luminfire.net/ops/tooling/ci/gitlab-ci-templates/-/tree/master/deploy-runcloud-laravel-mix

stages:
  - solcare
  - test
  - build
  - deploy

include:
  - project: 'templates/gitlab/ci-templates'
    file:
      - 'presets/all.yml'
      - 'presets/php.yml' # because lockfiles depends on it
      # - 'test/php-syntax-check.yml'
      # - 'test/WP/phpunit.yml'
      - 'security/lockfiles.yml'
      # - 'build/wp-plugin-with-npm.yml'
      # - 'deploy/documentation/brilliantsolutions-docsify.yml'
