# Tests, builds, and deploys a WordPress site to Runcloud.
# See https://git.luminfire.net/ops/tooling/ci/gitlab-ci-templates/-/tree/master/deploy-runcloud-laravel-mix

stages:
  - test
  - build
  - deploy

include:
  - project: 'templates/gitlab/ci-templates'
    file:
      # - 'test/php-syntax-check.yml'
      # - 'test/WP/phpunit.yml'
      - 'security/lockfiles.yml'
      # - 'build/wp-plugin-with-npm.yml'
      # - 'deploy/documentation/brilliantsolutions-docsify.yml'


deploy:
  stage: deploy
  tags:
    - docker
  image: node:latest
  script:
    - npm config set @luminfire:registry https://gitlab.luminfire.net/api/v4/packages/npm/
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish
